version: '3.5'
services:
  flaskapp:
    container_name: distnace_api
    build: .
    volumes:
      - .:/opt/services/flaskapp/src
      - ./app/logs/:/app/logs/distance.log
    ports:
      - "5050:5000"
